### ISSUE TITLE
Epic: Backports for v1.13.0-rc2

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1149]
## Summary

We're going to need a `v1.13.0-rc2`.

Here are some PRs that should be backported to it. Some of these should be done as their own PR while others can be combined.
- [x] #1154 
  <- #1137
  <- #1141
  <- #1150 
- [x] #1155 
  <- #1140 
  <- #1144 
  <- #1146
  <- #1147
  <- #1163 
  <- #1164 
  <- #1165
  <- #1156 
- [x] #1162 
  <- #1148 
- [x] #1166 
  <- #1138 
  <- #1139 
  <- #1133 
  <- #1098 
- [x] #1167
  <- #1158
- [x] #1170 
  <- #1168
- [x] #1182
  <- #1173

The PRs listed above are the original PRs to `main`.

To backport them to `release/v1.13.x`:
1. `git checkout main && git pull`
2. Use `git log --oneline` to identify the commit hash of the PR(s) desired.
3. `git checkout release/v1.13.x && git pull`
4. `git checkout -b <user>/bp-<something>`
5. Use `git cherry-pick <commit hash>` to apply a PR to your branch.
6. If there are any conflicts, fix them and commit.
7. Repeat 5 and 6 for each PR in the group.
8. Create a new PR from your branch with `release/v1.13.x` as the target branch.
9. A merge commit would better help git track similarities between `main` and `release/v1.13.x`. A squash and merge just makes the merge back to `main` a little messier.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
