### ISSUE TITLE
Epic: Metadata and wasm

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1440]
## Summary

This is an epic to track issues related to updates to the `x/metadata` module in order to make it easier to use, and useable with wasm. The end goal is to make it easier to for smart contracts to use the `x/metadata` module.

## Issues

- [x] #1279 
- [x] #1280 
- [x] #1381 
- [x] #1437 
- [x] #1438 
- [ ] #1439
- [x] #1443

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
Since there's only one issue left in this, I'm going to go ahead and close it.
