### ISSUE TITLE
Metadata module cli tx commands

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#162]
## Summary

Add a collection of `tx` commands to the metadata module so basic work can be done to create/edit metadata structures can be done from the command line

## Problem Definition

Currently there are extensive query options for the cli metadata interface but only extremely limited tx (add-scope only) methods.

## Proposal

Create the ability to manage basic metadata information using the cli.  Ensure that commands use flags or optional parameters to leave off fields that are not required or can otherwise be empty (such as value-owner on a scope)

These items should be completed as separate tickets (edit with reference to new ticket numbers)

- [x] Add/Update/Remove Scope (Issue #199) - (See #169 for updated naming conventions)
  - [x] Add/Remove data-access entry on scope - (Issue #220)
  - [x] Add/Remove/Replace owner on scope - should be able to add a new owner or replace existing owner with a new one (Issue #283)
- [x] Add/Update/Remove Record in Scope - requires a recordspecification id which in turn includes a contract specification, optional session_id, if not given would create a new session using the associated contract specification.  This will fail if the scope has a scopespecification that does not include the provided contractspecification as an authorized method of maintenance.  It must be possible to specify the array of parties in order to satisfy the contractspecification (Issue #205)
- [x] Add/Update/Remove Scope Specification (Issue #202)
  - [ ] Add/Remove Contract Specification from Scope Specification* (Issue #302)
- [x] Add/Update/Remove Contract Specification* (Issue #195)
  - [x] Add/Remove RecordSpecification.*
- [x] Add/Update/Remove Record Specification* (Issue #176)
- [x] For Session note that Delete is not required (removed when no longer referenced) and this must be created in conjunction with an Add Record request.

_* Note that changing specifications will naturally have some issues with existing data validation, it is the assumption that these rules go into effect for future updates and will not invalidate existing data_
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Added link to #169 in description for tracking the rename from `Addxxxxx` to `Writexxxxx` rpc endpoints

**Comment by channa-figure** [comment]
Add new issue #176 for Add/Update/Remove Record Specification.
