### ISSUE TITLE
Epic: Exchange Module

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1658]
## Summary

Build an `x/exchange` module to facilitate the buying and selling of assets.

## Problem Definition

Currently, exchanges of assets can only be done with either a smart contract or the groups module.

Each of those has downsides, though. Notably, the assets are sent to an intermediary account while waiting for finalization/clearing/settlement.

## Proposal

Create an `x/exchange` module that utilizes in-place holds and allows owners to put their assets up for sale, and for buyers to express desire to buy.

The module will allow creation of markets that are responsible for match making (among other things). Users can then submit asks and bids using their assets, which are placed in hold until settled or cancelled.

The markets will be able to collect order submission fees and settlement fees, and the exchange (blockchain) will receive a small cut of that.

## Sub-tasks

- [x] #1698
- [ ] #1699
- [ ] #1700
- [ ] #1701
- [ ] #1702
- [ ] #1703

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
Closed since this shipped with `v1.17.0`, even though there's still some stuff to add later.
