### ISSUE TITLE
Refine Metadata Module API

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#169]
## Summary

After review of the initial metadata module api there were some concerns identified surrounding the use of MetadataAddress and the components within.  In addition the naming of the tx msg endpoints could be a little more clear.

## Problem Definition

The MetadataAddress structure is useful for internal kvstore handling of records in the metadata module.  Unfortunately due to its byte array nature and use of byte code/encoding it represents challenges for clients to use.  In light of this an optional "one-of" style of use in the endpoints can be added to support either requests using the components or the address directly at the preference of the client.  A further option of exploring the use of the result message to return the metadata addresses of items added/updated in the query can be explored and adopted if the SDK supports this correctly.

## Proposal

The following refinements are proposed for the metadata module api

- [x] Remove Memorialize Contract/ChangeOwnership rpc endpoints from tx.proto (tx.proto#L18-21)
- [x] For each of the methods that creates new records on chain add a result that includes the address of any updated records
    - [x] AddScope (rename to WriteScope)
    - [x] AddSession (rename to WriteSession)
    - [x] AddRecord (rename to WriteRecord)
    - [x] AddScopeSpecification (rename to WriteScopeSpecification)
    - [x] AddContractSpecification (rename to WriteContractSpecification)
    - [x] AddRecordSpecification (rename to WriteRecordSpecification)
- [x] Update tx messages to allow users to provide either components or addresses for the id fields. Do not alter on-chain storage though.
    - [x] Scope
    - [x] Session
    - [x] Record
    - [x] ScopeSpecification
    - [x] ContractSpecification
    - [x] RecordSpecification
- [x] Update all the queries to make them easier to use by allowing uuids or bech32 address strings
    - [x] Scope
    - [x] ~~SessionContextByUUID / SessionContextByID~~ Combined into new Sessions query
    - [x] ~~RecordsByScopeUUID / RecordsByScopeID~~ Combined into new Records query
    - [x] Ownership
    - [x] ValueOwnership
    - [x] ScopeSpecification
    - [x] ContractSpecification
    - [x] ~~ContractSpecificationExtended~~ Combined into the ContractSpecification query
    - [x] RecordSpecificationsForContractSpecification
    - [x] ~~RecordSpecification / RecordSpecificationByID~~ Combined into new Records query
- [x] Consider cleaning up the cli queries by using some of these simplifications.
- [x] Add queries for getting all entries
    - [x] ScopesAll
    - [x] SessionsAll
    - [x] RecordsAll
    - [x] ScopeSpecificationsAll
    - [x] ContractSpecificationsAll
    - [x] RecordSpecificationsAll

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned
