### ISSUE TITLE
Epic: SDK v0.50

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#1760]
## Summary

This epic is for identifying and coordinating the work for bumping Cosmos SDK to `v0.50.x`.

## Overview

We will need to make changes across at least two repos, this one and our fork of the SDK. We'll need to do a few key things that then allow us to do some work in parallel. In general, we will be commenting a bunch of stuff out and re-adding it all back in.

As we disable stuff, mark things with todo comments that reference this issue, e.g. `// TODO[1760]: Add the marker module back in.` These comments should give us a nice list of work to do if we do something like `grep -rF 'TODO[1760]' *` 

When you pick up a checklist item, make an issue from it and assign it to yourself (so that we know someone's working on it). Use the "convert to issue" thing (right side when you hover over a checklist item) for this. It's okay to have a PR that checks off multiple things.

## The Plan

1. In this repo, use a `main-v0.50` branch that we will create PRs to. We'll start it off by switching the SDK to `v0.50.x` and commenting out a lot of stuff, then we'll work on fixing everything and putting it all back together.
2. In our SDK fork, use a `release-pio/v0.50.x` branch that starts with a `v0.50.x` tag and re-applies our customizations.
3. We can still make changes to `main`, but those will eventually need to be backported to `main-v0.50`.
4. Once or SDK fork is ready, tag our version and switch us over to that in the `main-v0.50` branch.
5. Once `main-v0.50` is done, merge it back into `main`.

## Provenance Repo Plan

These should be done in this order.

- [x] 1. Identify and Finish any key changes needed that aren't related to `v0.50.x`.
- [x] #1771
- [x] #1772
- [x] 4. From the resulting `TODO[1760]`s compile a general list of things to work on and add entries to the TODOs checklist.
- [x] 5. Finish some TODOs in the checklist by making PRs to `main-v0.50`.
- [x] 6. Backport any PRs in `main` that aren't yet in `main-v0.50`.
- [x] 7. Merge `main-v0.50` back into `main`.
- [x] 8. Finish all TODOs in the checklist by making PRs to `main`.

## Provenance Repo Pre-Work

These are the key changes that need to be done before we start the `v0.50` work in this repo.

- [x] #1498 

## Provenance Repo TODOs

These can (mostly) be done in any order and can be grouped together for PRs as needed. An entry that starts with a tag has related TODOs in the repo.

Example command for finding TODO entries for a tag:
```
grep --color --recursive --include '*' --include '.*' --exclude-dir .git --exclude-dir vendor --exclude statik.go -F 'TODO[1760]: account'
```

- [x] `account`: Add the account keeper back to the app. PR #1844 
- [x] `auth`: Add the auth keeper back to the app. PR #1844
- [x] `authz`: Add the authz keeper back to the app. PR #1844
- [x] `bank`: Add the bank keeper back to the app. PR #1844
- [x] `capability`: Add the capability keeper back to the app. PR #1844
- [x] `crisis`: Add the crisis keeper back to the app. PR #1844
- [x] `distr`: Add the distribution keeper back to the app. PR #1844
- [x] `evidence`: Add the evidence keeper back to the app. PR #1844
- [x] `feegrant`: Add the feegrant keeper back to the app. PR #1844
- [x] `gov`: Add the gov keeper stuff back to the app. PR #1844
- [x] `ica-host`: Add the icahost back to the app. PR #1844
- [x] `mint`: Add the mint module back to the app. PR #1844
- [x] `slashing`: Add the slashing keeper back to the app. PR #1844
- [x] `staking`: Add the staking keeper back to the app. PR #1844
- [x] `upgrade`: Add the upgrade keeper back to the app. PR #1844
- [x] `wasm`: Add the wasm keeper back to the app, and fix a couple provwasm sim parts.
- [x] #1902
- [x] #1901
- [x] Get rid of support for now-unsupported db types: ClevelDB, BoltDB and BadgerDB. PR #1862 
- [x] Ensure we're creating/handling/getting the codecs correctly See also the "cosmossdk.io/simapp/params".EncodingConfig struct.
- [x] Fix empty rewards events. Delete Legacy Amino stuff.
- [x] Add PreBlocker thing: https://github.com/cosmos/cosmos-sdk/blob/v0.50.1/UPGRADING.md#set-preblocker. PR #1859 
- [x] Decide if we want anything from the confix command: https://github.com/cosmos/cosmos-sdk/blob/v0.50.1/UPGRADING.md#config-files (nope).
- [x] Update CLI setup for auto-cli stuff: https://github.com/cosmos/cosmos-sdk/blob/v0.50.1/UPGRADING.md#autocli
- [x] Setup textual sign mode: https://github.com/cosmos/cosmos-sdk/blob/v0.50.1/UPGRADING.md#textual-sign-mode
- [x] Migrate the legacy gov props to msgs (might be optionaln, not sure, but needs to be done at some point).
- [x] Register the new gRPC base node queries: https://github.com/cosmos/cosmos-sdk/blob/v0.47.6/UPGRADING.md#grpc
- [x] Remove imports of "cosmossdk.io/simapp": https://github.com/cosmos/cosmos-sdk/blob/v0.47.6/UPGRADING.md#simapp
- [x] Remove emission of EventTypeMessage events (now done automatically).
- [x] Add crisis store: https://github.com/cosmos/cosmos-sdk/blob/v0.47.6/UPGRADING.md#xcrisis. PR #1861 
- [x] ~~Add proposers to old proposals (in the upgrade): https://github.com/cosmos/cosmos-sdk/blob/v0.47.6/UPGRADING.md#new-proposalproposer-field~~ Can only affect current, open proposals, and stuff needs to be hard-coded, so we probably don't care about this.
- [x] `app-module`: Add assertions of new interface types with each module definition, Ensure the BasicModuleManager is correct, and get rid of the global ModuleBasics variable (in `app/app.go`).
- [x] `auto-cli`: Ensure we still get the GetAccount and Block commands.
- [x] `broadcast`: Fix unit tests that depend on submitting a tx and getting a result. https://github.com/cosmos/cosmos-sdk/blob/v0.47.6/UPGRADING.md#broadcast-mode
- [x] `cli`: Grab ReadPageRequestWithPageKeyDecoded from our fork and switch back to it.
- [x] `finalize-block`: Refactor a bunch of tests to use FinalizeBlock (was BeginBlock/EndBlock stuff). #1873 
- [x] `genutil`: Add some genutil commands back in.
- [x] `gov-cli`: Grab GenerateOrBroadcastTxCLIAsGovProp and related stuff from our fork of the SDK and restore its uses.
- [x] `proto`:  Update protos that use sdk.Int and sdk.Dec (now sdkmath .Int and .LegacyDec). Make sure all tx requests have a signer option. Make sure any interface-related options are correct. https://github.com/cosmos/cosmos-sdk/blob/v0.47.6/UPGRADING.md#acceptsimplements_interface-proto-annotations PR #1844
- [x] `proto`: Update proto depenency retrieval. Update proto generation and management. Use cosmos/gogoprotoinstead of gogo/protobuf: https://github.com/cosmos/cosmos-sdk/blob/v0.47.6/UPGRADING.md#protobuf Regenerate the protos.
- [x] `rosetta`: See what's up with this now. Add it back in or clean up the TODOs.
- [x] `signers`: Update MsgCreateTriggerRequest validation because ValidateBasic() can't get signers anymore.
- [x] `signing`: Fix tests that do their own thing to sign Txs. #1873 
- [x] `streaming`: Ensure that the new streaming stuff is sufficient.
- [x] `sync-info`: Figure out how to keep this route where it is.
- [x] `yaml`: Decide if we care about a yaml-related test.
- [x] `attribute`: Delete the NewHandler and migrate the tests to the keeper.
- [x] `marker`: Delete the marker handler and migrate handler tests to the keeper.
- [x] `metadata`: Delete the metadata  handler and migrate handler tests to the keeper.
- [x] `name`: Delete the name handler.
- [x] `reward`: Delete the reward handler. Clean up some event attribute stuff.
- [x] `marker`: Delete the marker querier.
- [x] `metadata`: Delete the metadata querier. 
- [x] `bank`: Remove a couple entries from the marker's expected keeper.
- [x] `async-icq`: Add this back once they have a v0.50 compatible version.
- [x] `bank`: Figure out how to use the bank queries in the CLI tests.
- [x] `gov`: Fix tests/sims that try to get the last proposal or update gov params.
- [x] `ibc`: Switch back to our fork of ibc-go or clean up the TODO in go.mod.
- [x] `ibc-host`: Figure out where the ibchost stuff moved and add the stuff back to the app.
- [x] `params`: Add migration of consensus params to the upgrade. https://github.com/cosmos/cosmos-sdk/blob/v0.47.6/UPGRADING.md#xconsensus
- [x] `consensus`: Add new [module registration](https://github.com/cosmos/cosmos-sdk/blob/main/UPGRADING.md#xconsensus) for `consensus` module to the upgrade handler (0.47.x migration)
- [x] `params`: Create module migrations to move params to their own stores: metadata, marker, name, attribute, msgfees, reward, trigger, ibctransfer, ibc-hooks. #1935 
- [x] `params: See what's up with ibc-host, ica-host, and icq params. (these params are being migrated via the migrations pattern.  We still need to initialize these stores and send them to their respective keepers)
- [x] Identify new gov (and other) params and set them appropriately.
- [x] `wasm`: Switch back to our fork (or delete the TODO in go.mod).
- [x] `sdk`: Bump the SDK back to a version from our fork.
- [x] `count-authz`: Fix some tests once this is back in the SDK.
- [x] `event-history`: Replace the event history stuff once we have it back in the SDK. #1873 
- [x] `fee-handler`: Replace the fee handler stuff once we have it back in the SDK. PR #1862
- [x] `locked-coins`: Replace the locked coins stuff once we have it back in the SDK.
- [x] `msg-service-router`: Switch back to the PioMsgServiceRouter once IMsgServiceRouter is back in the SDK. Ensure ours is still in-line with what the SDK has (plus our alterations). PR #1844
- [x] Call `bankkeeper.MigrateParamsProv` in the upgrade handlers.
- [x] `msg-service-router`: registerHybridHandler was added in v0.50 we need to figure out if we need to add msg fee logic to it
- [x] `exchange`: Restore commented functionality once the better InputOutputCoins is back in the SDK.
- [x] Audit changes to config files and consider switching back to the SDK's client.config. Ensure the pre-upgrade command works as expected.
- [x] Ensure all tests pass again (and aren't just commented out).
- [x] Identify and fix uses of deprecated stuff.
- [x] `github`: Restore some github-action related stuff.
- [x] Make the linter pass again.
- [x] Make sure the SDK's swagger stuff is up to date, pull it in and make sure all our proto and swagger stuff is up-to-date too.
- [x] Assure all proto txs have `option (cosmos.msg.v1.signer) = "<signer>"` and remove the `GetSigners` methods.  Also, make sure tx msg has been tested with sim or other method where it has been signed. 
- [x] Remove `rewards` module
- [x] Backport changes made to `main` since splitting off `main-v0.50`.
- [x] Review the stargate whitelist to make sure it's got everything we need.
- [x] Create `Getparams` and `SetParams` endpoints for the modules that have params, but don't have those endpoints.
- [x] Ensure there are no more `TODO[1760]` comments.
- [x] Update Github branch protection rules to require the linter and tests to pass again.
- [x] Review the spec docs to ensure that the proto links in the spec docs are correct.
- [x] Add the circuit breaker module.

## Cosmos-SDK Fork Plan

These should be done in this order.

- [x] 1. Identify the differences we've made to our fork. Add entries to the TODOs checklist for each.
- [x] 2. Create the `release-pio/v0.50.x` branch from the most recent `v0.50.x` tag.
- [x] 3. Finish all the TODOs in the checklist by making PRs to `release-pio/v0.50.x`.
- [x] 4. Tag a new version.
- [ ] 5. Make `main-pio` match `release-pio/v0.50.x`.

## Cosmos-SDK Fork TODOs

- [x] Start a fresh branch based on upstream's most recent v0.50 tag. -> https://github.com/provenance-io/cosmos-sdk/tree/release/v0.50.x
- [x] Audit our differences for v0.46.13 and add anything missing to this list.
- [x] EventManager: NewEventManagerWithHistory, GetABCIEventHistory, runTx (Fee events and event aggregator), baseapp.Simulate also returns a context, simulation.SimulateFromSeed also returns the last block time, Propagate event history in EndBlock.
- [x] Fee Handler: Add FeeHandler back to baseapp, switch back to IMsgServiceRouter. https://github.com/provenance-io/cosmos-sdk/pull/593
- [x] Streaming: Double check that what's in the SDK is in line with what we have/need.
- [x] CountAuthorization: Add it back in.
- [x] Add the allow_list back to the SendAuthorization.
- [x] Double check the SendEnabled stuff (make sure they didn't put the whole list back in a single params object).
- [x] Put the UpdateDenomMetadata back into the bank module.
- [x] Pruning cmd: get existing viper instead of a new one.
- [x] Send Restrictions: Should be able to use what the SDK has now, but need to double check. If we have a different `InputOutputCoins` func signature, we'll want that to switch back to that and make our own copy of that func.
- [x] Locked Coins: Add it back in.
- [x] Make sure there's still a CLI command for getting spendable balances.
- [x] In the rootmulti store's `buildCommitInfo` method, sort the keys by name first.
- [x] Fix genesis account number handling (in the x/auth Genesis stuff).
- [x] Have authz.MsgExec.ValidateBasic() also run `ValidateBasic` on all its msgs.
- [x] Better handling for when no handler exists for a gov prop.
- [x] Fix group sims' account picker to always pick different accounts.
- [x] Update the bank module migrations since we added one that the SDK doesn't have.

**Comment by SpicyLemon** [comment]
If you find more thing that need to be done (that you're not just handling as you find it), feel free to update the checklists.

**Comment by SpicyLemon** [comment]
This command can be used to check compilation of all the unit tests:
```console
$ go test -mod=readonly  -tags='cgo ledger test_ledger_mock norace' -run='ZYX_NOPE_NOPE_XYZ' ./...
```

**Comment by SpicyLemon** [comment]
I put this info in #1943, but figure it'd be good to put here too.

Here's some info on the tests that still fail:
* `github.com/provenance-io/provenance/app` - Need to fix the bank migration. Getting this panic from the umber upgrade tests: `"parameter SendEnabled not registered"`
* `github.com/provenance-io/provenance/cmd/provenanced/cmd`:
  * `cmd/provenanced/cmd/config_test.go` - Need to update with updated config data.
  * `cmd/provenanced/cmd/pre_upgrade_test.go` - There's a TODO in the RootCmd.PersistentPreRunE about the client context that I think is causing a test to fail here.
* `github.com/provenance-io/provenance/internal/antewrapper` - Still some TODOS left in here.
* `github.com/provenance-io/provenance/x/ibchooks` - These all fail with `"tx parse error"` indicating that some codec isn't being shared/used as expected.
  * In `vendor/github.com/cosmos/cosmos-sdk/x/auth/tx/decoder.go`: Error coming back from unknownproto.RejectUnknownFields: `unable to resolve type URL /ibc.lightclients.tendermint.v1.ClientState`
  * Need to add the `ibctm "github.com/cosmos/ibc-go/v8/modules/light-clients/07-tendermint"` module to the app so that the codec stuff is registered.
  * Then, need to bump the max gas because this is the new error: `transaction gas exceeds maximum allowed; got: 10000000 max allowed: 4000000: tx too large`
* `github.com/provenance-io/provenance/x/ibcratelimit/module` - "tx parse error"
* `github.com/provenance-io/provenance/x/ibcratelimit/simulation` - This fails because a msg that should be a gov prop is not being submitted as a gov prop.
* `github.com/provenance-io/provenance/x/oracle/simulation`
  * `TestSimulateMsgSendQueryOracle` fails because the op msg is not okay. It has the comment "cannot get random channel because none exist".
  * `TestSimulateMsgUpdateOracle` fails because a msg that should be a gov prop is not being submitted as a gov prop.

**Comment by SpicyLemon** [comment]
The work for this bump is done, so I'm closing this epic!
