### ISSUE TITLE
Add Kafka indexing support

### ISSUE THREAD

**Issue by egaxhaj** [provenance-io/provenance#540]
## Summary

Provide the ability to store state changes to Kafka.

## Problem Definition

Why do we need this feature? 
- _Provide the ability to save the state to an external storage system._

What problems may be addressed by introducing this feature?
- _It provides a means of listening to state changes as they occur in real time and storing them in Kafka for further processing._

What benefits does the Provenance Network stand to gain by including this feature?
- _Reduced the complexity of having to maintain and spring up new query nodes as the blockchain size increases._

Should this feature be implemented in the Cosmos SDK directly?  Consider submitting
 this request upstream instead.
- _Yes. See [ADR-038 Implementation](https://github.com/cosmos/cosmos-sdk/issues/10096).

Are there any disadvantages of including this feature? 
- _Requires knowledge and expertise of Kafka architecture and API.

## Proposal

Discussion: https://github.com/cosmos/cosmos-sdk/discussions/10351
Plugin system proposal: https://github.com/cosmos/cosmos-sdk/pull/11175
Implementation: https://github.com/provenance-io/cosmos-sdk/pull/49

## Sub Items

- [x] https://github.com/provenance-io/cosmos-sdk/pull/37
- [x] https://github.com/provenance-io/cosmos-sdk/pull/38
- [x] https://github.com/provenance-io/cosmos-sdk/pull/49
- [x] https://github.com/provenance-io/cosmos-sdk/pull/64
- [x] #712
- [x] #785
- [x] #786

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by egaxhaj-figure** [comment]
Releases in `v1.8.2`
