### ISSUE TITLE
Add expiration process to scopes

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#689]
## Summary

Add a new property to scope records that tracks an expiration blockheight.

## Problem Definition

Currently scopes can be written once and maintained in the active state of the blockchain forever.  This update would add a property for tracking a blockheight at which the scope data can be purged.  With this property in place a process can be created that will remove the scope after a period of time when it has not been used.

## Proposal

A process that allows any account to submit the information needed for the chain to remove the record and be rewarded for doing so will be more efficient than trying to scan/query the chain at the end of every block for eligible scope records to purge.  In order to encourage users to perform these actions a reward payment should be made for successfully submitting the request to remove the resource.  The first successful expire request would be paid a bounty while subsequent requests would fail.  The reward would be distributed using the fees collected during the creation of scopes.

 
- [ ] #694
- [ ] #693
- [ ] #692
- [ ] #691
   - For scopes that have expired allow any address to make the call and expire the asset.  
   - For scopes that have not yet expired require the standard modification rules to apply (asset owner/value owner signatures, etc)
- [ ] #695

The rewards component of purging the scope will be handled separately by the APE incentive module.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by egaxhaj** [comment]
Closing this as a duplicate. Work is now being tracked in #957
