### ISSUE TITLE
[EPIC] Add metadata query functionality

### ISSUE THREAD

**Issue by dwedul-figure** [provenance-io/provenance#75]
This is a meta ticket focusing on tickets that add querying capabilities.

## Summary

Add the ability to query the chain for various pieces of data in various formats.

## Problem Definition

There's data on the chain, and we need to be able to get at it.

## Proposal

Basic queries:
- [x] Get a scope by scope id #53
- [x] Get a session by session id #55
- [x] Get a record by record id #54
- [x] Get a scope spec by scope spec id #56
- [x] Get a contract spec by contract spec id  #57
- [x] Get a record spec by record spec id #59

Extended queries:
- [x] Get scopes by party address #53
- [x] Get scopes by value owner address #53
- [x] Get sessions by scope id #53
- [x] Get records by scope id #54
- [x] Get scope uuids by owner address #54
- [x] Get extended session info (session, records and all specs involved) by session id #169
- [x] Get extended scope info (scope, scope spec, and extended session infos) by scope id #169
- [x] Get scope spec uuids by contract spec id #169
- [x] Get extended contract spec (contract specs, record specs, and scope spec uuids) by contract spec id #59
- [x] Get extended scope spec (scope specs and extended contract specs) by scope spec id #169
- [x] Get scope specs by owner address #169
- [x] Get extended contract specs by owner address #169

Get All queries (paginated):
- [x] Get all scopes #169
- [x] Get all sessions #169
- [x] Get all Records #169
- [x] Get all scope specs #169
- [x] Get all contract specs #169
- [x] Get all record specs #169 

Work for these should be done in separate tickets. Once those tickets are created, please update this ticket to indicate which ticket goes with a specific checklist item.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned
