### ISSUE TITLE
Create authz authorization with limited number of uses.

### ISSUE THREAD

**Issue by dwedul-figure** [provenance-io/provenance#807]
## Summary

Create an authorization for use with `x/authz` that restricts the authorization to a number of uses.

## Problem Definition

As an asset owner, I want to give authorization to a grantee that is limited to a certain number of times, so that I can more accurately restrict the authorization.

## Proposal

Create a new authorization message that has a uses left count and an underlying authorization.

`MsgTypeURL` should return the `MsgTypeURL` of the underlying authorization.
`Accept` should check and update the uses left and also call the `Accept` of the underlying authorization.
`ValidateBasic` should make sure the uses left is greater than zero and call the underlying authorization's `ValidateBasic`.

This will be similar to the `SendAuthorization` implementation in https://docs.cosmos.network/master/architecture/adr-030-authz-module.html#authorization except with a uses left count instead of coins, and the addition of the underlying authorization.

As part of this, we will also want to update all custom uses of authorizations (e.g. in the `x/metadata` module) to call the `Accept` method and make sure they allow for this new type of authorization (e.g. aren't limited to a generic authorization). If any such limitations exist, check for this type of authorization, and then limit off of its underlying type. In other words, don't allow this type of authorization without checking the underlying type.

Also, make sure that we can use the `provenanced tx authz` command stuff to add this new type of authorization.

Subtasks:
- [x] #904
- [x] #905
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dwedul-figure** [comment]
This issue was created due to this comment: https://github.com/provenance-io/provenance/issues/788#issuecomment-1105752816 on #788

**Comment by egaxhaj** [comment]
Found a bug #903 in the marker module that blocks part of the work for this.

**Comment by egaxhaj** [comment]
Closing this. Subtasks #904 and #905 have been completed and merged.
