### ISSUE TITLE
NFT Module Integration Epic

### ISSUE THREAD

**Issue by derekadams** [provenance-io/provenance#956]
## Summary

This epic will use the Cosmos SDK NFT APIs included in Cosmos 0.46 to interact with the existing Provenance NFT implementation made available in the metadata module. We may also add additional support for ERC20 token APIs that interact with the existing Provenance marker module.

## Problem Definition

The Cosmos SDK NFT APIs will be hooked to a simple default implementation, but there is no simple approach to support mapping those API calls to the corresponding calls within Provenance. A new translation layer will need to be added which allows the Cosmos NFT API calls to be converted into one or more Provenance API calls, accounting for any data translation that needs to happen in the process.

## Proposal

* [x] #958 
* [x] #778 
* [x] #1487 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
ERC-20 support would be against the marker module so that's likely a separate effort

**Comment by iramiller** [comment]
I think this "NFT" api would make the most sense as an interface for the marketplace which also happens to implement the require NFT module apis so that we can cover IBC transfer requirements.

**Comment by iramiller** [comment]
On the marketplace front ... an api that let users submit asset pools for escrow and potentially do bilateral settlement would be very useful.  The escrow process would need to vet and lock down the marker permission set to ensure the asset is properly secured (removing admin, mint, deposit, withdraw grants, etc).
