### ISSUE TITLE
Update main readme.md with current milestone information and status.

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#96]
## Summary of Bug

The current readme.md file is out of date

## Remediation

- [ ] Status section should reflect current public testnet/mainnet. Reference to migration status of existing Figure private blockchain should be included
- [ ] Upcoming milestone section should be removed
- [ ] Add quick start section with link to gitbook documentation for Provenance and upstream SDK quick-start docs

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned
