### ISSUE TITLE
Cosmos 0.46.0 Integration Epic

### ISSUE THREAD

**Issue by derekadams** [provenance-io/provenance#960]
## Summary

This epic groups issues related to integration of the Cosmos `0.46.0` release into Provenance. There are a number of new features and updates that will require changes to the P8s code base in order to be compatible. During the process of integration, issues related to the P8e-specific fork of Cosmos may be added under this issue as well in order to track the changes.

## Problem Definition

The Cosmos `0.46.0` release contains many new features and updates that will require integration effort in the P8e code base. Until `0.46.0` is officially released, we will be working from the P8e Cosmos fork, but the end goal is to be able to use the official release soon after it is made available.

## Proposal

* [x] #970 
* [x] #800
* [x] #995
* [x] #1006
* [x] #1007 
* [x] #1008
* [x] #626 
* [x] #1077
* [x] #1099
* [x] #1101
* [x] #1104
* [x] #1097

[Child tasks to be added here for issues related to 0.46 integration]

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
Cosmos-SDK tag `v0.46.0-pio-1-rc1` has been created and should have everything we need to start trying to update to v0.46.0.

**Comment by SpicyLemon** [comment]
We're now on `v0.46.1-pio-1-rc1`.

**Comment by SpicyLemon** [comment]
Woo! We cut `v0.46.1-pio-1` today, and have switched to that.

**Comment by SpicyLemon** [comment]
Updated our fork with Cosmos-SDK `v0.46.2` and we're now on `v0.46.2-pio-1`.
