### ISSUE TITLE
Epic: Prepare a v0.46-based version in our fork

### ISSUE THREAD

**Issue by SpicyLemon** [provenance-io/provenance#970]
## Summary

With the release of [Cosmos-SDK v0.46](https://github.com/cosmos/cosmos-sdk/releases), we need to create our own version with our customizations applied to it.

The goal of this epic is to coordinate minimum amount of work that needs to be done in order to have a v0.46-based branch that we can use to start upgrading provenance to v0.46.

## Proposal

- [x] #971
- [x] Create the `release-pio/v0.46.x' branch.
- [x] #972
- [x] #973
- [x] ~~#974~~
- [x] #975 (???)
- [x] #976 (danny)
- [x] ~#977~
- [x] Tag `v0.46.0-pio-1-rc1` once everything is (hopefully) ready.

Notes:
* To make a change, branch off of `release-pio/v0.46.x`.
* Suggested branch name format is `prov/{user}/0.46-{change}`.
* Once everything on your branch looks good, PR it back into `release-pio/v0.46.x`, and make sure to SQUASH and merge it.
* There is a `Provenance Specific Releases` section in the changelog for you to put entries about your change.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
Turns out the upgrade order fix was not actually needed, as the SDK did have a fix for that.

Instead of just fixing `GetLastCompletedUpgrade`, their fix was to migrate how the completed upgrades are stored. Previously, they were `{key}{name}` -> `{height}`. Now they are `{key}{height}{name}` -> `1`. So we don't actually need to re-apply our own fix for `GetLastCompletedUpgrade` that we had applied to `v0.45`.

I've updated the checklist to reflect that.

**Comment by SpicyLemon** [comment]
Branch [release-pio/v0.46.0-pio-1](https://github.com/provenance-io/cosmos-sdk/tree/release-pio/v0.46.0-pio-1) has been created and tagged as [v0.46.0-pio-1](https://github.com/provenance-io/cosmos-sdk/blob/release-pio/v0.46.0-pio-1/RELEASE_NOTES.md).

Any further changes needed should be tracked as separate issues.

**Comment by SpicyLemon** [comment]
Branch [release-pio/v0.46.0-pio-1-rc1](https://github.com/provenance-io/cosmos-sdk/tree/release-pio/v0.46.0-pio-1-rc1) has been created and tagged as [v0.46.0-pio-1-rc1](https://github.com/provenance-io/cosmos-sdk/blob/v0.46.0-pio-1-rc1/RELEASE_NOTES.md).

This should have everything we need to start the update to v0.46.0. Any further changes needed should be done as separate tickets.
